import { MailtrapClient } from "mailtrap";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

/**
 * Mailtrap Email Utility
 * Sends bilingual emails (German + English) using Mailtrap templates
 * Templates are managed in the Mailtrap dashboard
 */

const client = new MailtrapClient({
  token: process.env.MAILTRAP_TOKEN || "",
});

const sender = {
  email: "noreply@kubikart.de",
  name: "Kubikart Team",
};

interface EmailParams {
  to: string;
  templateUuid: string;
  variables?: Record<string, string>;
  attachments?: EmailAttachment[];
}

interface EmailAttachment {
  filename: string;
  content: string;
  type?: string;
  disposition?: "attachment" | "inline";
}

const DEFAULT_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://kubikart-frontend.vercel.app";
const PUBLIC_DIR = path.join(process.cwd(), "public");

function statusLabel(status: string, locale: "de" | "en"): string {
  const labels: Record<string, { de: string; en: string }> = {
    pending: { de: "Zahlung ausstehend", en: "Payment pending" },
    processing: { de: "In Bearbeitung", en: "Processing" },
    completed: { de: "Versendet/Abgeschlossen", en: "Shipped/Completed" },
    "on-hold": { de: "Wartet auf Klärung", en: "On hold" },
    cancelled: { de: "Storniert", en: "Cancelled" },
    refunded: { de: "Erstattet", en: "Refunded" },
    failed: { de: "Zahlung fehlgeschlagen", en: "Payment failed" },
  };

  const resolved = labels[status] ?? { de: status, en: status };
  return locale === "de" ? resolved.de : resolved.en;
}

function resolveTemplateUuid(value: string | undefined, fallback: string): string {
  const trimmed = (value || "").trim();
  return trimmed.length > 0 ? trimmed : fallback;
}

function escapePdfText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[^\x20-\x7E]/g, "?");
}

function buildSimplePdf(lines: string[]): string {
  const contentParts = ["BT", "/F1 12 Tf", "50 790 Td"];

  lines.slice(0, 36).forEach((line, index) => {
    if (index > 0) {
      contentParts.push("0 -18 Td");
    }
    contentParts.push(`(${escapePdfText(line)}) Tj`);
  });

  contentParts.push("ET");
  const contentStream = contentParts.join("\n");

  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
    "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
    `5 0 obj\n<< /Length ${Buffer.byteLength(contentStream, "utf8")} >>\nstream\n${contentStream}\nendstream\nendobj\n`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += obj;
  }

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";

  for (let i = 1; i <= objects.length; i += 1) {
    pdf += `${offsets[i].toString().padStart(10, "0")} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, "utf8").toString("base64");
}

function buildOrderPdfAttachment(
  orderData: {
    orderNumber: string;
    total: string;
    items: Array<{ name: string; quantity: number; price: string }>;
    customer: { name: string };
    shipping: { address: string; city: string; postalCode: string };
  },
  locale: "de" | "en",
): EmailAttachment {
  const header = locale === "de" ? "Kubikart Bestellbestaetigung" : "Kubikart Order Confirmation";
  const itemLines = orderData.items.map((item) => `- ${item.quantity} x ${item.name} (EUR ${item.price})`);

  const lines = [
    header,
    "",
    `Order Number: ${orderData.orderNumber}`,
    `Customer: ${orderData.customer.name || "Customer"}`,
    `Total: EUR ${orderData.total}`,
    "",
    "Shipping Address:",
    `${orderData.shipping.address}`,
    `${orderData.shipping.postalCode} ${orderData.shipping.city}`,
    "",
    "Items:",
    ...itemLines,
    "",
    "Generated by Kubikart transactional email service.",
  ];

  return {
    filename: "order.pdf",
    content: buildSimplePdf(lines),
    type: "application/pdf",
    disposition: "attachment",
  };
}

function readOptionalPdfAttachment(relativePath: string, filename: string): EmailAttachment | null {
  const normalized = relativePath.replace(/^\/+/, "");
  const fullPath = path.join(PUBLIC_DIR, normalized);

  if (!existsSync(fullPath)) {
    return null;
  }

  const fileBuffer = readFileSync(fullPath);
  return {
    filename,
    content: fileBuffer.toString("base64"),
    type: "application/pdf",
    disposition: "attachment",
  };
}

function getLegalPdfAttachments(locale: "de" | "en"): EmailAttachment[] {
  const agbPath = process.env.MAIL_PDF_AGB_PATH || `legal/${locale}/agb.pdf`;
  const widerrufPath = process.env.MAIL_PDF_WIDERRUF_PATH || `legal/${locale}/widerruf.pdf`;

  const fallbackAgb = readOptionalPdfAttachment("legal/agb.pdf", "agb.pdf");
  const fallbackWiderruf = readOptionalPdfAttachment("legal/widerruf.pdf", "widerruf.pdf");

  const agb = readOptionalPdfAttachment(agbPath, "agb.pdf") || fallbackAgb;
  const widerruf = readOptionalPdfAttachment(widerrufPath, "widerruf.pdf") || fallbackWiderruf;

  return [agb, widerruf].filter((item): item is EmailAttachment => Boolean(item));
}

function resolveStatusVariant(status: string, trackingUrl?: string): "pending" | "processing" | "shipped" | "delivered" | "failed" | "refunded" {
  if (status === "pending" || status === "on-hold") {
    return "pending";
  }

  if (status === "processing") {
    return "processing";
  }

  if (status === "completed") {
    return trackingUrl ? "shipped" : "delivered";
  }

  if (status === "refunded") {
    return "refunded";
  }

  if (status === "shipped") {
    return "shipped";
  }

  if (status === "delivered") {
    return "delivered";
  }

  return "failed";
}

function resolveStatusTemplateUuid(statusVariant: "pending" | "processing" | "shipped" | "delivered" | "failed" | "refunded"): string {
  const fallback = resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ORDER_STATUS, "");

  switch (statusVariant) {
    case "pending":
      return resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ORDER_STATUS_PENDING, fallback);
    case "processing":
      return resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ORDER_STATUS_PROCESSING, fallback);
    case "shipped":
      return resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ORDER_STATUS_SHIPPED, fallback);
    case "delivered":
      return resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ORDER_STATUS_DELIVERED, fallback);
    case "refunded":
      return resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ORDER_STATUS_REFUNDED, fallback);
    case "failed":
      return resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ORDER_STATUS_FAILED, fallback);
    default:
      return fallback;
  }
}

/**
 * Send an email using a Mailtrap template
 * Templates include both German and English versions
 */
export async function sendEmail({ to, templateUuid, variables = {}, attachments = [] }: EmailParams): Promise<void> {
  if (!process.env.MAILTRAP_TOKEN) {
    console.error("MAILTRAP_TOKEN not configured");
    return;
  }

  if (!templateUuid) {
    throw new Error("Missing Mailtrap template UUID");
  }

  try {
    await client.send({
      from: sender,
      to: [{ email: to }],
      template_uuid: templateUuid,
      template_variables: variables,
      attachments,
    });
  } catch (error) {
    console.error("Email send error:", error);
    throw error;
  }
}

/**
 * Newsletter confirmation email
 * Template ID: Set this to your Mailtrap template ID
 */
export async function sendNewsletterConfirmation(email: string, confirmationUrl: string, locale: "de" | "en" = "de"): Promise<void> {
  await sendEmail({
    to: email,
    templateUuid: resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_NEWSLETTER, ""),
    variables: {
      confirmation_url: confirmationUrl,
      locale,
    },
  });
}

/**
 * Order confirmation email
 * Sent after successful payment
 */
export async function sendOrderConfirmation(
  email: string,
  orderData: {
    orderId: number;
    orderNumber: string;
    total: string;
    items: Array<{ name: string; quantity: number; price: string }>;
    customer: { name: string };
    shipping: { address: string; city: string; postalCode: string };
  },
  locale: "de" | "en" = "de",
): Promise<void> {
  const itemsList = orderData.items.map((item) => `${item.name} × ${item.quantity} - €${item.price}`).join("\n");
  const attachments = [buildOrderPdfAttachment(orderData, locale), ...getLegalPdfAttachments(locale)];

  await sendEmail({
    to: email,
    templateUuid: resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ORDER, ""),
    variables: {
      order_id: orderData.orderId.toString(),
      order_number: orderData.orderNumber,
      customer_name: orderData.customer.name,
      items: itemsList,
      shipping_address: `${orderData.shipping.address}, ${orderData.shipping.postalCode} ${orderData.shipping.city}`,
      total: orderData.total,
      locale,
      legal_agb_url: `${DEFAULT_SITE_URL}/${locale}/legal/agb`,
      legal_withdrawal_url: `${DEFAULT_SITE_URL}/${locale}/legal/widerruf`,
      legal_privacy_url: `${DEFAULT_SITE_URL}/${locale}/legal/datenschutz`,
    },
    attachments,
  });
}

/**
 * Password reset email
 * Sent via WordPress backend, but defined here for reference
 */
export async function sendPasswordReset(email: string, resetUrl: string, locale: "de" | "en" = "de"): Promise<void> {
  await sendEmail({
    to: email,
    templateUuid: resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_PASSWORD_RESET, ""),
    variables: {
      reset_url: resetUrl,
      locale,
    },
  });
}

/**
 * Contact form notification
 * Sent to admin and confirmation to user
 */
export async function sendContactConfirmation(
  email: string,
  contactData: {
    name: string;
    message: string;
    type: string;
  },
  locale: "de" | "en" = "de",
): Promise<void> {
  await sendEmail({
    to: email,
    templateUuid: resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_CONTACT, ""),
    variables: {
      customer_name: contactData.name,
      inquiry_type: contactData.type,
      message: contactData.message,
      locale,
    },
  });
}

export async function sendWithdrawalConfirmation(
  email: string,
  data: {
    receiptId: string;
    receivedAt: string;
    name: string;
    contractReference: string;
    scope: string;
    locale: "de" | "en";
  },
): Promise<boolean> {
  const templateUuid = resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_WITHDRAWAL, "");
  if (!process.env.MAILTRAP_TOKEN || !templateUuid) {
    return false;
  }

  await sendEmail({
    to: email,
    templateUuid,
    variables: {
      receipt_id: data.receiptId,
      received_at: data.receivedAt,
      customer_name: data.name,
      contract_reference: data.contractReference,
      withdrawal_scope: data.scope || (data.locale === "de" ? "Gesamter Vertrag" : "Entire contract"),
      locale: data.locale,
    },
  });
  return true;
}

/**
 * Welcome email after newsletter subscription
 * Sent after double opt-in confirmation
 */
export async function sendNewsletterWelcome(email: string, locale: "de" | "en" = "de"): Promise<void> {
  await sendEmail({
    to: email,
    templateUuid: resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_NEWSLETTER_WELCOME, ""),
    variables: {
      locale,
    },
  });
}

/**
 * Account creation email
 */
export async function sendAccountCreated(email: string, customer: { firstName: string; lastName: string }, locale: "de" | "en" = "de"): Promise<void> {
  await sendEmail({
    to: email,
    templateUuid: resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_ACCOUNT_CREATED, ""),
    variables: {
      customer_name: `${customer.firstName} ${customer.lastName}`.trim(),
      locale,
      account_url: `${DEFAULT_SITE_URL}/${locale}/account`,
      legal_privacy_url: `${DEFAULT_SITE_URL}/${locale}/legal/datenschutz`,
    },
  });
}

/**
 * Login/security alert email
 */
export async function sendLoginAlert(
  email: string,
  data: { customerName?: string; ipAddress: string; userAgent: string; loginTimeIso: string },
  locale: "de" | "en" = "de",
): Promise<void> {
  await sendEmail({
    to: email,
    templateUuid: resolveTemplateUuid(process.env.MAILTRAP_TEMPLATE_LOGIN_ALERT, ""),
    variables: {
      customer_name: data.customerName || "",
      login_time_iso: data.loginTimeIso,
      login_ip: data.ipAddress,
      user_agent: data.userAgent,
      locale,
      account_url: `${DEFAULT_SITE_URL}/${locale}/account`,
      contact_url: `${DEFAULT_SITE_URL}/${locale}/kontakt`,
    },
  });
}

/**
 * Order status update email (payment pending, processing, shipped/completed, etc.)
 */
export async function sendOrderStatusUpdate(
  email: string,
  orderData: {
    orderId: number;
    orderNumber: string;
    status: string;
    customerName: string;
    trackingUrl?: string;
  },
  locale: "de" | "en" = "de",
): Promise<void> {
  const statusVariant = resolveStatusVariant(orderData.status, orderData.trackingUrl);

  await sendEmail({
    to: email,
    templateUuid: resolveStatusTemplateUuid(statusVariant),
    variables: {
      order_id: orderData.orderId.toString(),
      order_number: orderData.orderNumber,
      customer_name: orderData.customerName,
      order_status: orderData.status,
      order_status_label: statusLabel(orderData.status, locale),
      order_status_variant: statusVariant,
      tracking_url: orderData.trackingUrl || "",
      locale,
      account_url: `${DEFAULT_SITE_URL}/${locale}/account`,
      legal_agb_url: `${DEFAULT_SITE_URL}/${locale}/legal/agb`,
      legal_withdrawal_url: `${DEFAULT_SITE_URL}/${locale}/legal/widerruf`,
    },
  });
}
